### json 요청
POST http://localhost:12345/gongsiGeomsaeg
Content-Type: application/json

{
  "corp_code":"",
  "bgn_de":"20200117",
  "end_de":"20200117",
  "last_reprt_at":"",
  "pblntf_ty":"",
  "pblntf_detail_ty":"",
  "corp_cls":"Y",
  "sort":"",
  "sort_mth":"",
  "page_no":"1",
  "page_count":"10"
}